export type Category = 'tv-film' | 'editorial' | 'commercial' | 'all';

export interface Project {
  id: number;
  title: string;
  subtitle: string;
  client: string;
  category: Category;
  categoryLabel: string;
  type: string;
  role: string;
  description: string;
  thumbnailUrl: string;
  previewVideoUrl: string;
  fullVideoUrl: string;
}

export const projects: Project[] = [
  {
    id: 1,
    title: 'The Greatest Love',
    subtitle: 'Story Never Told',
    client: 'Amazon Originals & Artists Equity',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Feature Documentary',
    role: 'Director, Cinematographer, Executive Producer',
    description: 'The Greatest Love Story Never Told follows Jennifer Lopez as she independently produces a new album and cinematic original chronicling her twenty-year journey to self-love. With candid moments and insight from her closest collaborators, the film offers an intimate portrait of an icon reclaiming her narrative and embracing self-acceptance.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b8787_1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/GREATEST%20LOVE%20STORY%20NEVER%20TOLD.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/GREATESTLOVESTORYNEVERTOLD.mp4',
  },
  {
    id: 2,
    title: 'Barbara Palvin',
    subtitle: "Harpers Bazzar",
    client: "Harper's Bazaar",
    category: 'editorial',
    categoryLabel: 'Editorial',
    type: 'Fashion Film',
    role: 'Director & DP',
    description: "A stunning fashion film for Harper's Bazaar Greece featuring supermodel Barbara Palvin in an intimate editorial showcasing high fashion in breathtaking locations.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87ab_1-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial/BARBARAPALVIN_DESCTOP.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial+full/BarbaraPalvinxHarpersBazaarGreece.mp4',
  },
  {
    id: 3,
    title: 'Stand Up',
    subtitle: 'Seattle Reign FC',
    client: 'Voyeur Verite & Seattle Reign FC',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Short Documentary',
    role: 'Director & DP',
    description: 'Stand Up is a short film that captures the heart and soul of Seattle Reign FC through music, community, and sport. Directed by award-winning filmmaker Jason Bergh and featuring a new anthem by Seattle artist Brittany Davis, the film channels the team\'s spirit and legacy into a powerful call for unity and celebration.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b8788_2.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/STAND%20UP.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/STANDUP.mp4',
  },
  {
    id: 4,
    title: 'Sasha Calle',
    subtitle: 'YSL',
    client: 'YSL X Flaunt',
    category: 'editorial',
    categoryLabel: 'Editorial',
    type: 'Fashion Film',
    role: 'Director & DP',
    description: 'An evocative fashion film pairing actress Sasha Calle with YSL for Flaunt Magazine, blending cinematic storytelling with high-fashion aesthetics.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87ac_2-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial/SASHACALLE_DESKTOP.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial+full/SashaCallexFlauntxJasonBergh.mp4',
  },
  {
    id: 5,
    title: 'Noted',
    subtitle: 'Alicia Keys',
    client: 'YouTube Originals & Westbrook',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Five Part Docu-Series',
    role: 'Showrunner & Executive Producer',
    description: 'Noted: Alicia Keys The Untold Stories, from showrunner Jason Bergh, offers an intimate look at Alicia Keys as she celebrates the twentieth anniversary of Songs in A Minor while creating her eighth record. Spanning four episodes, the series highlights pivotal moments in her journey from childhood and early career struggles to creative collaborations with artists like J. Cole and Swae Lee.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b8789_3.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/NOTED.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/NOTEDALICIAKEYSTRAILER.mp4',
  },
  {
    id: 6,
    title: 'Lenny Kravitz',
    subtitle: 'Balmain',
    client: 'Balmain X Flaunt',
    category: 'editorial',
    categoryLabel: 'Editorial',
    type: 'Fashion Film',
    role: 'Director & DP',
    description: 'A powerful fashion film featuring rock icon Lenny Kravitz for Balmain x Flaunt Magazine, capturing his raw energy and irreplaceable style.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87ad_3-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial/LENNY%20KRAVITZ.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial+full/FLAUNT192GETTINAROUNDLENNYKRAVITZFLAUNTFILM.mp4',
  },
  {
    id: 7,
    title: 'Halftime',
    subtitle: 'Jennifer Lopez',
    client: 'Netflix & Make Make Studios',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Feature Film',
    role: 'Director Of Photography & Executive Producer',
    description: 'Halftime offers an intimate and long awaited look into the life of Jennifer Lopez, going beyond the spotlight to reveal the woman behind the icon. More than a concert documentary, the film grants unprecedented access to Lopez\'s private world.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b878a_4.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/HALFTIME.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/HALFTIMEJENNIFERLOPEZ.mp4',
  },
  {
    id: 8,
    title: "Life's a Trip",
    subtitle: 'Trippie Redd',
    client: 'Snapchat Originals & Trooper Entertainment',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: '8 Part Docuseries',
    role: 'Director & Showrunner',
    description: "Life's A Tripp is a docuseries starring rapper Trippie Redd as he explores pressing social and political issues across America, with a focus on Los Angeles. Through candid conversations and immersive on-the-ground experiences, the series tackles topics such as race, policing, homelessness, and mental health.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b878b_5.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/LIFES%20A%20TRIP.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/LIFESATRIPTRIPPIEREDDTRAILER.mp4',
  },
  {
    id: 9,
    title: 'Migos',
    subtitle: 'Tiny Desk',
    client: 'NPR x OBB Pictures',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Tiny Desk Series',
    role: 'Director',
    description: "Migos brought their signature energy to NPR's Tiny Desk. Shot during COVID at the Gallery Department showroom in Los Angeles, the session reimagined their biggest hits in an intimate setting.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b878c_6.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/MIGOS.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/MIGOSTINYDESK.mp4',
  },
  {
    id: 10,
    title: 'Ismael',
    subtitle: 'Cruz Cordova',
    client: 'Flaunt',
    category: 'editorial',
    categoryLabel: 'Editorial',
    type: 'Fashion Film',
    role: 'Director & DP',
    description: 'An intimate and cinematic fashion film for Flaunt Magazine starring actor Ismael Cruz Cordova.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87ca_7-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial/Flaunt%20Films%20Ismael.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial+full/FlauntFilmsIsmaelCruzCordova22.mp4',
  },
  {
    id: 11,
    title: "Hard Lovin' Woman",
    subtitle: 'Juliette Lewis',
    client: 'Red Bull x UX Entertainment',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Documentary',
    role: 'Showrunner & Executive Producer',
    description: "Hard Lovin' Woman is a documentary from showrunner Jason Bergh and director Michael Rapaport that follows actress and musician Juliette Lewis as she steps away from Hollywood to chase her passion for rock and roll.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b878d_7.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/HARD%20LOVIN%20WOMAN.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/HardLovinWoman.mp4',
  },
  {
    id: 12,
    title: 'When the Garden',
    subtitle: 'Was Eden',
    client: 'ESPN 30 for 30 x UX Entertainment',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Feature Film',
    role: 'Showrunner & Executive Producer',
    description: "This ESPN 30 for 30 documentary chronicles the story of the New York Knicks' iconic championship teams of 1970 and 1973, highlighting the unique blend of personalities and talent that came together under Coach Red Holzman.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b878e_8.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/WHEN%20THE%20GARDEN%20WAS%20EDEN.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/WhenTheGardenWasEdenEmmyWinner.mp4',
  },
  {
    id: 13,
    title: 'A Thousand Words',
    subtitle: 'Michelle Obama',
    client: 'BET HER',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'TV Special',
    role: 'Director & Executive Producer',
    description: 'A Thousand Words with Michelle Obama features former First Lady Michelle Obama in a candid conversation with Valerie Jarrett, former Senior Advisor to President Barack Obama.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b878f_9.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/MichelleObama.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/MichelleObama_InAThousandWords.mov',
  },
  {
    id: 14,
    title: 'Saturday',
    subtitle: 'Night Live',
    client: 'NBC',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Short Documentary',
    role: 'Director & DP',
    description: "Jennifer Lopez's Week at SNL offers a rare behind the scenes look at her weeklong journey hosting Saturday Night Live. Directed by Jason Bergh, the short film captures the highs, challenges, and creative intensity of preparing for one of television's most iconic live shows.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b8790_10.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/SATURDAY%20NIGHT%20LIVE.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/SATURDAYNIGHTLIVE.mp4',
  },
  {
    id: 15,
    title: 'Street Dreams',
    subtitle: 'Feature Film',
    client: 'Rob Dyrdek, Paul Rodriguez, and Ryan Dunn',
    category: 'tv-film',
    categoryLabel: 'TV & Film',
    type: 'Feature Film',
    role: 'Executive Producer',
    description: "Street Dreams is set in the heart of the Midwest, a place where skateboard culture feels foreign and misunderstood. It follows Derrick Cabrera, a gifted young skater fighting against the odds. Produced by Rob Dyrdek and starring Paul Rodriguez Jr., Street Dreams has become a cult classic with over 100 million views worldwide.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b8792_12.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film%20and%20TV/STREET%20DREAMS.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Film+and+TV+full/StreetDreamsOfficialTrailer.mp4',
  },
  {
    id: 16,
    title: 'Katseye',
    subtitle: 'InStyle',
    client: 'InStyle',
    category: 'editorial',
    categoryLabel: 'Editorial',
    type: 'Digital Cover',
    role: 'Director & DP',
    description: 'A dynamic digital cover shoot for InStyle Magazine featuring K-pop group Katseye, blending fashion and music in a striking visual narrative.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87ae_4-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial/KATSEYE.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial+full/KATSEYEMOTIONCOVER.mp4',
  },
  {
    id: 17,
    title: 'RZA',
    subtitle: 'Hunger',
    client: 'Hunger',
    category: 'editorial',
    categoryLabel: 'Editorial',
    type: 'Fashion Film',
    role: 'Director & DP',
    description: 'A striking fashion film featuring Wu-Tang Clan founder RZA for Hunger Magazine, merging street culture with high fashion in a cinematic visual statement.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87af_5-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial/RZA.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial+full/RZAxHUNGER.mov',
  },
  {
    id: 18,
    title: 'Bryan Cranston',
    subtitle: "Gentleman's Journal",
    client: "Gentleman's Journal",
    category: 'editorial',
    categoryLabel: 'Editorial',
    type: 'Fashion Film',
    role: 'Director & DP',
    description: "A sophisticated fashion film featuring acclaimed actor Bryan Cranston for Gentleman's Journal, capturing his commanding presence and impeccable style.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87b0_6-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial/BRYAN%20CRANSTON.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Editorial+full/BryanCranstonXGentlemansJournal.mov',
  },
  {
    id: 19,
    title: 'Bayou',
    subtitle: 'With Love',
    client: "Summer 25'",
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: "SS'25",
    role: 'Director & DP',
    description: 'A lush, sun-soaked commercial for Bayou With Love, capturing the brand\'s effortless elegance for their Summer 2025 collection.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b879a_11-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/BAYOU%2025_1.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/BAYOU25.mp4',
  },
  {
    id: 20,
    title: 'Genesis',
    subtitle: 'Electric',
    client: 'Electric Concept Vehicle Launch',
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: 'Commercial',
    role: 'Director & DP',
    description: 'A cinematic launch film for Genesis Electric Concept Vehicle in California, showcasing the intersection of luxury and innovation.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b879b_1-2.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/GENESIS.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/GENESISXCALIFORNIALAUNCHFILM.mp4',
  },
  {
    id: 21,
    title: 'March Madness',
    subtitle: 'Mazda',
    client: '#iwanttothank',
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: 'Commercial',
    role: 'Director & DP',
    description: 'A heartfelt commercial for Mazda during March Madness, celebrating the people who inspire and support us along the way.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b879c_3-2.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/MAZDA%20MARCH%20MADNESS.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/MAZDAMARCHMADNESS.mp4',
  },
  {
    id: 22,
    title: 'Oscars',
    subtitle: 'Mazda',
    client: '#IWantToThank',
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: 'Oscars 2025',
    role: 'Director & DP',
    description: 'An emotional Oscars 2025 spot for Mazda, weaving together personal stories of gratitude and achievement.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b879d_2-2.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/MAZDA%20OSCARS.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/MAZDAOSCARS.mp4',
  },
  {
    id: 23,
    title: 'The Mother',
    subtitle: 'Netflix',
    client: 'NETFLIX Marketing',
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: 'Social Media Marketing',
    role: 'Director & DP',
    description: 'A powerful social media marketing campaign for Netflix\'s The Mother, capturing the intensity and emotion of the film.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b879e_17-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/THE%20MOTHER.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/THEMOTHER.mp4',
  },
  {
    id: 24,
    title: 'DSW',
    subtitle: 'JLO',
    client: 'DSW',
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: 'JLO Shoe Collection',
    role: 'Director & DP',
    description: 'A vibrant commercial for the JLO shoe collection at DSW, capturing Jennifer Lopez\'s signature glamour and energy.',
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87a5_16-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/JLO_DSW.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/JLODSW.mp4',
  },
  {
    id: 25,
    title: 'JLO Beauty',
    subtitle: 'Launch',
    client: 'JLO Beauty',
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: 'The Launch',
    role: 'Director & DP',
    description: "The launch film for Jennifer Lopez's revolutionary JLO Beauty skincare line, celebrating radiance and self-love.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87a3_8-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/JLO%20BEAUTY%20LAUNCH.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/JLOBEAUTYLAUNCH.mp4',
  },
  {
    id: 26,
    title: 'Hershey\'s',
    subtitle: 'Appreciation',
    client: 'UM GLOBAL',
    category: 'commercial',
    categoryLabel: 'Commercial',
    type: 'Branded Content',
    role: 'Director & DP',
    description: "A warm and celebratory branded content piece for Hershey's, honoring summertime appreciation and connection.",
    thumbnailUrl: 'https://cdn.prod.website-files.com/696e26954ee505294b4b8653/696e26954ee505294b4b87a8_15-1.webp',
    previewVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercials/HErsheys.mp4',
    fullVideoUrl: 'https://d3b24qxei2vojx.cloudfront.net/Commercial/HersheysSummertimeAppreciation.mp4',
  },
];

export const navLinks = [
  { num: '01.', label: 'Work', href: '/' },
  { num: '02.', label: 'Reportage', href: '/reportage' },
  { num: '03.', label: 'About', href: '/about' },
  { num: '04.', label: 'Archive', href: '/archive' },
  { num: '05.', label: 'Contact', href: '/contact' },
];
